import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/router';
import AdminLayout from '@/components/layout/AdminLayout';
import {withAuth} from '@/components/auth/withAuth';
import {useAuthStore} from '@/lib/auth/store';
import {productRequest} from '@/lib/products/client';
type Media={id:string;path:string;name:string;width:number|null;height:number|null;bytes:number|null;created_at:string|null;references:{id:string;title:string;status:string}[]};
const button='border rounded-lg px-3 py-2 text-sm disabled:opacity-40';
function MediaPage(){
 const {user,logout}=useAuthStore(),router=useRouter();
 const [media,setMedia]=useState<Media[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[selected,setSelected]=useState<Media|null>(null);
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[usage,setUsage]=useState('all'),[page,setPage]=useState(0),[total,setTotal]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await productRequest(`/api/admin/product-media?page=${page}&search=${encodeURIComponent(query)}&usage=${usage}`);setMedia(r.media);setUrls(r.image_urls);setTotal(r.total);setMore(r.has_more);}catch(e){setError(e instanceof Error?e.message:'图片读取失败');}finally{setLoading(false);}},[page,query,usage]);
 // Fetching synchronizes this page with the server and exposes its loading state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 const upload=async(files:FileList|null)=>{if(!files?.length||busy)return;setBusy(true);setError('');setNotice('');let count=0;try{for(const file of Array.from(files)){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>3*1024*1024)throw new Error(`${file.name}：请选择不超过 3 MB 的 JPG、PNG 或 WebP`);await productRequest('/api/admin/product-media',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file});count++;}setNotice(`已上传 ${count} 张图片，可在编辑产品页面从图片银行库选择。`);await load();}catch(e){setError(`${count?`已上传 ${count} 张；`:''}${e instanceof Error?e.message:'上传失败'}。已成功上传的图片会保留。`);}finally{setBusy(false);}};
 if(!user)return null;
 return <AdminLayout user={user} onLogout={async()=>{await logout();await router.push('/login');}}><div className="mb-6"><h1 className="text-2xl font-bold">图片银行库</h1><p className="text-sm text-slate-500 mt-2">集中查看已上传及现有产品使用的图片。在编辑产品页面选择复用；图片上传不会发布产品。</p></div>
 <div className="bg-white border rounded-xl p-5 mb-4 flex flex-wrap items-center gap-4"><label className="text-sm text-blue-700">上传图片<input className="block mt-2 max-w-full text-sm" type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void upload(e.target.files);e.target.value='';}}/></label><p className="text-xs text-slate-500">每张最多 3 MB · JPG / PNG / WebP</p>{busy&&<p role="status">正在上传…</p>}</div>
 {notice&&<p role="status" className="p-4 bg-green-50 text-green-800 mb-4 rounded">{notice}</p>}{error&&<p role="alert" className="p-4 bg-red-50 text-red-800 mb-4 rounded">{error}<button className="underline ml-3" onClick={()=>void load()}>重新读取</button></p>}
 <form className="flex flex-wrap gap-3 mb-4" onSubmit={e=>{e.preventDefault();setPage(0);setQuery(search);}}><input aria-label="搜索图片名称" className={`${button} flex-1 min-w-48 bg-white`} placeholder="搜索图片名称" value={search} onChange={e=>setSearch(e.target.value)}/><button className={`${button} bg-white`}>搜索</button><select aria-label="图片关联状态" className={`${button} bg-white`} value={usage} onChange={e=>{setUsage(e.target.value);setPage(0);}}><option value="all">全部图片</option><option value="published">关联已发布产品</option><option value="draft">仅关联草稿或下架产品</option><option value="unused">未关联产品</option></select></form>
 {loading?<p role="status" className="p-8">正在读取图片…</p>:!error&&<><p className="text-xs text-slate-500 mb-3">共 {total} 张图片</p><div className="grid grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 gap-4">{media.map(m=><button key={m.id} className="bg-white border rounded-xl p-3 text-left hover:border-blue-500" onClick={()=>setSelected(m)}><div className="relative aspect-square"><Image unoptimized fill sizes="220px" className="object-contain" src={urls[m.path]} alt={m.name}/></div><p className="text-sm truncate mt-3">{m.name}</p><p className="text-xs text-slate-500 mt-1">{m.width?`${m.width} × ${m.height}`:'现有产品图片'}{m.bytes?` · ${Math.ceil(m.bytes/1024)} KB`:''}</p><p className="text-xs text-slate-500 mt-1">{m.created_at?new Date(m.created_at).toLocaleDateString('zh-CN'):'上传时间未记录'}</p><p className="text-xs text-blue-700 mt-2">关联 {new Set(m.references.map(r=>r.id)).size} 个产品 · 查看图片</p></button>)}</div>{!media.length&&<p className="text-center p-12 text-slate-500">暂无符合条件的图片</p>}<div className="flex justify-between mt-5"><button className={button} disabled={!page} onClick={()=>setPage(page-1)}>上一页</button><button className={button} disabled={!more} onClick={()=>setPage(page+1)}>下一页</button></div></>}
 <dialog ref={dialog} onCancel={()=>setSelected(null)} className="m-auto w-[calc(100%-2rem)] max-w-2xl rounded-xl p-5 backdrop:bg-slate-900/50" aria-label="图片详情">{selected&&<><div className="flex justify-between gap-3"><h2 className="font-semibold break-all">{selected.name}</h2><button autoFocus className={button} onClick={()=>setSelected(null)}>关闭</button></div><div className="relative h-72 my-4"><Image unoptimized fill sizes="600px" className="object-contain" src={urls[selected.path]} alt={selected.name}/></div><h3 className="font-medium text-sm mb-2">关联产品</h3><div className="max-h-48 overflow-auto space-y-2">{selected.references.map(r=><Link className="block text-sm text-blue-700" key={`${r.id}:${r.status}`} href={`/admin/products/${r.id}`}>{r.title} · {r.status==='published'?'已发布':r.status==='archived'?'已下架':'草稿'}</Link>)}</div>{!selected.references.length&&<p className="text-sm text-slate-500">暂未关联产品。可在编辑产品页面复用。</p>}</>}</dialog>
 </AdminLayout>;
}
export default withAuth(MediaPage);
